apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook
namePrefix: gb-local-
resources:
  - ../../base
  - namespace.yaml
patches:
  # Example patch (optional). Remove if not needed.
  # - path: patch-replicas.yaml
