apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app.kubernetes.io/name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
    spec:
      containers:
        - name: echoserver
          image: registry.k8s.io/echoserver:1.10
          ports:
            - name: http
              containerPort: 8080