apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app.kubernetes.io/name: guestbook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: guestbook
  ports:
    - name: http
      port: 80
      targetPort: 8080
